### ISSUE TITLE
Can't deploy gateway app to cloud

### ISSUE THREAD

**Issue by xiaoyan-huang-bhc3** [Enterprise-connect/ec-x-sdk#23]
Hi Support Team,

When I try to push the gateway app with the latest release hokkaido.212, it through the following errors.

Is hokkaido.212 not compatible with our EC service?

Any help would be really appreciated!

> 2019-11-25T09:49:46.50-0700 [APP/PROC/WEB/0] OUT  [EC Agent] main pacakge exception: EC Service is invalid. Contact your EC Service administrator for more detail.

> 2019-11-25T09:53:18.18-0700 [APP/PROC/WEB/0] OUT  [EC Gateway] 2019/11/25 16:53:18 [usage reported.]
> 2019-11-25T09:53:20.01-0700 [CELL/0] ERR Failed to make TCP connection to port 8080: connection refused
> 2019-11-25T09:53:20.01-0700 [CELL/0] ERR Timed out after 1m0s: health check never passed.

**Comment by ayasuda2OO3** [comment]
Thanks for raising the issue here, this helps us to build a better and reusable kb. @crysxyh.

EC services relevant to GE Digital's cloud foundry predix CF1 were all up-to-date. Additionally, the usage flags has been updated following [the announcement of the 203+ releases](https://github.com/Enterprise-connect/ec-x-sdk/releases/tag/v1.hokkaido.203) the flag ```-lpt``` has been deprecated whereas ```-gpt``` was introduced to the usage of gateway/gw:client/gw:server modes to meet the increasing requirement. Please refer to [the internal agent document for more in detail](https://github.build.ge.com/Enterprise-Connect/agent#D3).

Please share your gateway config here (**hashout the secret**) if further clarification needed. Thanks!

**Comment by xiaoyan-huang-bhc3** [comment]
Thanks @ayasuda2003!
This is my gateway configuration.
`#!/bin/bash
./ecagent_linux_sys -mod "gateway" -lpt "${PORT}" -zon "zone_id_here" -sst "https://zone_id_here.run.aws-usw02-pr.ice.predix.io" -tkn "token_here" -dbg`

This is my server configuration.
`./ecagent_linux_sys -mod "server" -grp "zone_id_here" -zon "zone_id_here" -sst "https://zone_id_here.run.aws-usw02-pr.ice.predix.io" -aid "zXHRHf" -cid "client_id_here" -csc "client_secret_here" -dur "84000" -hst "wss://gateway-zone_id_here.run.aws-usw02-pr.ice.predix.io/agent" -oa2 "oa2_url" -rht "db_url" -rpt "5432" -hca "${PORT}" -dbg`

If lpt is deprecated, should I change the gateway config as below?
`#!/bin/bash
./ecagent_linux_sys -mod "gateway" -gpt "${PORT}" -zon "zone_id_here" -sst "https://zone_id_here.run.aws-usw02-pr.ice.predix.io" -tkn "token_here" -dbg`

Thanks for your attention again!
Xiaoyan

**Comment by ayasuda2OO3** [comment]
> If lpt is deprecated, should I change the gateway config as below?

Yes.

**Comment by xiaoyan-huang-bhc3** [comment]
Thanks a lot!  It works.
