### ISSUE TITLE
 - Invalid Client Access for GE Power

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#31]
Deploy a client agent onprem. However, in the case with Power, the access is not available with the internal-facing LBer due to the client proxy setting. **Need to deploy a external-facing LBer for the interim**.

**Comment by ayasuda2OO3** [comment]
ETA of this task is EoB Frioday (Dec-13) @ramaraosrikakulapu

**Comment by ramaraosrikakulapu** [comment]
Following up and waiting for approvals to create external load balancers in customer VPC

**Comment by ramaraosrikakulapu** [comment]
Power team not able to create an external load balancer due to limitations. So decided to follow below approaches and test the connectivity - 

- [Run server and client in same VPC in different instances](https://github.com/Enterprise-connect/ec-x-sdk/issues/39)
- [Run server and client agents in different VPC's](https://github.com/Enterprise-connect/ec-x-sdk/issues/40)
- [Run the server agent in 'on prem' and client in AWS VPC](https://github.com/Enterprise-connect/ec-x-sdk/issues/46)

Created issues for each scenario
