### ISSUE TITLE
Genpact Connectivity Usecase between AWS FDL Database and  Predix SCx application

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/ec-x-sdk#33]
Latest-
1) The deployment script has been provided to the team.
2) The team is working on testing the script.

**Comment by ramaraosrikakulapu** [comment]
- Provided EC scripts for connecting to Kerberos System and HIVE database in AWS.

 - Customer tested the Kerberos system from terminal via EC connection and got successful response and then successfully connected to HIVE DB with another EC connection. 

 - Now customer team working on changes to the client application and make EC connections from it.

**Lesson learned** :- We were facing an issue while connecting target system and noticed the following exception in EC server logs - 
```
[exception occurred in wsocket client reading. err: websocket: close 1006 (abnormal closure): unexpected EOF  (session# cv9DhMK0Lr  bind# cQjfTqqo7O )]
```
Issue caused due to different version of client agent. Downloaded the agent with same version as gateway and server and solved the problem.
